import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Ticket Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="flexc flex-col h-screen max-h-screen bg-gray-100">
          <Navbar />
          <main className="flex-grow overflow-y-auto bg-gray-800 min-h-screen  text-black">{children}</main>
        </div>
      </body>
    </html>
  );
}
